### ISSUE TITLE
Add the fact that you must pass the whole store.state in the component data

### ISSUE THREAD

**Issue by jrmi** [mdartic/vue-reactive-store#11]
In the Readme, it took time for me to realize that i mustn't use a `store.state.property` in my component data but the  global `store.state` object.

Don't
```js
import store from '../store'

export default {
  data: {
    myStoreProperty: store.state.myStoreProperty
  },
  …
}
```
Do:

```js
import store from '../store'

export default {
  data: {
    state: store.state
  }, 
 …
}
```

**Comment by mdartic** [comment]
Yup, you're right.

I think it's a limitation of Vue's reactivity system.

I'll update the README to be explicit on this case.

**Comment by mdartic** [comment]
Please check https://github.com/mdartic/vue-reactive-store/pull/15 and tell me if it's ok to you.

**Comment by mdartic** [comment]
Well, in fact I'm going to merge because I have to push a new version of the package.

**Comment by mdartic** [comment]
If it's ok for you, please close the issue.

**Comment by jrmi** [comment]
Fine for me.
